services:
  - name: imagination-portal
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DATABASE_URL
        value: postgresql://codex_sync_db_user:KfunTyRtyuVHJK0Mnoxat3h0ZOQSdYbQ@dpg-d35onb8dl3ps739404ug-a.virginia-postgres.render.com/codex_sync_db
